### ISSUE TITLE
error[E0658]: use of unstable library feature 'try_from' (see issue #33417)

### ISSUE THREAD

**Issue by pepoospina** [gnunicorn/substrate-verifiable-credentials-workshop#2]
I had an old rust version as the default one and had to update to the latest one by running
 
```
rustup update stable
rustup default stable
```

This solved the issue

**Comment by gnunicorn** [comment]
All of substrate requires latest rust stable. But probably good to mention that if people come with a previously install rust.

**Comment by gnunicorn** [comment]
Looks like the bash script is doing that now - if you run it, it will update default. If you have previously changed default, we assume you are capable of fixing this ;) .
